
name: Run Docker image

#Manually triggered workflow
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [run_tests]

jobs:

  pull-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull Docker image
      run: docker pull egideon/cyber-reaper
      
    - name: Run Docker image
      run: docker run --rm egideon/cyber-reaper
